export const signalServiceABI = [
  { inputs: [], name: "B_NULL_APP_ADDR", type: "error" },
  { inputs: [], name: "B_WRONG_CHAIN_ID", type: "error" },
  { inputs: [], name: "B_ZERO_SIGNAL", type: "error" },
  { inputs: [], name: "RESOLVER_DENIED", type: "error" },
  { inputs: [], name: "RESOLVER_INVALID_ADDR", type: "error" },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint8", name: "version", type: "uint8" }],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
      { indexed: true, internalType: "address", name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "addressManager",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "app", type: "address" },
      { internalType: "bytes32", name: "signal", type: "bytes32" },
    ],
    name: "getSignalSlot",
    outputs: [{ internalType: "bytes32", name: "signalSlot", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_addressManager", type: "address" }],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "srcChainId", type: "uint256" },
      { internalType: "address", name: "app", type: "address" },
      { internalType: "bytes32", name: "signal", type: "bytes32" },
      { internalType: "bytes", name: "proof", type: "bytes" },
    ],
    name: "isSignalReceived",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "app", type: "address" },
      { internalType: "bytes32", name: "signal", type: "bytes32" },
    ],
    name: "isSignalSent",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "bool", name: "allowZeroAddress", type: "bool" },
    ],
    name: "resolve",
    outputs: [{ internalType: "address payable", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "chainId", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "bool", name: "allowZeroAddress", type: "bool" },
    ],
    name: "resolve",
    outputs: [{ internalType: "address payable", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "signal", type: "bytes32" }],
    name: "sendSignal",
    outputs: [{ internalType: "bytes32", name: "storageSlot", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
